# Generated by Django 5.0.1 on 2024-01-04 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='text',
            new_name='topic',
        ),
    ]
