# Generated by Django 5.0.1 on 2024-01-04 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_rename_text_topic_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic',
            new_name='text',
        ),
    ]
