# Generated by Django 5.0.1 on 2024-01-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_alter_topic_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='owner',
        ),
    ]
